name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: mdrxtech/actions/pnpm-setup@pnpm-setup_v0.1.2
        with:
          npmToken: ${{ secrets.NPM_PUBLISHING_TOKEN }}
          install: true
          nodeVersion: 18.18.0
          pnpmVersion: 8.8.0

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISHING_TOKEN }}
