name: Test

on:
  push:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: mdrxtech/actions/pnpm-setup@pnpm-setup_v0.1.2
        with:
          npmToken: ${{ secrets.PRIVATE_NPM_REGISTRY_ACCESS_TOKEN }}
          install: true
          nodeVersion: 18.18.0
          pnpmVersion: 8.8.0

      - name: Type check
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build

